### ISSUE TITLE
No set chest from dragons anymore

### ISSUE THREAD

**Issue by mattpilf** [aikaterna/gobcog#134]
Nobody seems to be getting set chest anymore from dragons.

**Comment by Drapersniper** [comment]
They still drop,  be logic was changed recently to increase their rarity

**Comment by mattpilf** [comment]
> They still drop, be logic was changed recently to increase their rarity

I mean from what I've gathered we've at least 30 -50 some dragon and still haven't gotten one. Just how rare is it supposed to be?

**Comment by Drapersniper** [comment]
It’s still RNG, if you had 50 bosses and didn’t get one that’s just very bad luck (not that with higher rebirths the odd does increase)

**Comment by mattpilf** [comment]
I mean I personally have had 40 rebirths and still none in the dozens of bosses, and others in 20-30 rebirths.

**Comment by Drapersniper** [comment]
They are still being rewarded, before they were too common, so their drop rate was cut to about a 1/3.  With that going to about 1/2 of original with higher rebirths, but it is RNG, besides dragons were never guaranteed set chests before they just had a chance of giving them.

**Comment by mattpilf** [comment]
Alright I'll be patient, seems like I and many others have been having some "really" bad luck then even if its 1/3 as common as before.

**Comment by Drapersniper** [comment]
Sorry i was misremembering rebirths do not affect chance.

However yes the change of the being sgown has been cut down to about a 3rd while increasing legendary and epic drops.

**Comment by kwando1313** [comment]
Yeah, I don't think this is just bad luck here, I think something is actually wrong as well - like we have a server for adventure, and none of us who have played have gotten a set in the last 4 days.

Sure, it's possible that we all have tremendously horrible luck, but I'd think the odds of that happening is extremely low.

**Comment by Drapersniper** [comment]
Just to make it 100% clear, as far as the cog goes it is behaving as expected and there is nothing broken here. Set chests are stop rewarded from bosses, just not as common as they were before

**Comment by mattpilf** [comment]
Ahh okay. From what I see there's a roll 1-10, with a 9 having a 1 in 13 chance of a set chest and a 10 having a 2 in 14 chance. Overall a 1 in 45.5 chance. Still seems like we've been unlikely but much more plausible. So given even just 80 set chest and 100 % success, with 10 dragons a day killed you're looking at a year minimum and likely closer to two years to get full set of everything.

Some might think that's a bit much, but whatever that is subjective. 

Related (unsure if I should open up a new issue for this), if you're at the point where you're looking to complete the set items there's no real incentive to kill regular monsters. Like it just becomes a wait till someone gets a dragon or even to start adventures and not even attack unless it's a dragon/boss(something I've seen).

One way to have an incentive would be to convert legendary into set items, even at a rate of 50 to 1 or higher with high rebirth. This would have no real benefit to anyone starting out, but provide an incentive to keep playing for more advanced players and keeping activity going. That also balances the epic to legendary conversion rates, so it would be sub optimal for anyone not looking for a set item.

**Comment by kwando1313** [comment]
Looking at the numbers, it looks like a chance for getting a set has dropped from 20% to a 2% chance - was it intended to drop that low?

At least to me, having the number at such a low rate discourages me from playing as like... I really don't see a point of playing since I'm (like matt) basically just trying to roll to get set pieces at this point...

**Comment by Drapersniper** [comment]
I have a very simple question for you all, you said in 40-50 dragons you didn’t see anything.

Over how long did you see those 40-50 dragons ?

**Comment by Drapersniper** [comment]
Set chest conversion from legendary is a no from me, Aika may be willing to do so but from me is a no, there is only 86 set pieces at the current moment in time and until more are added the odd of getting a set chests should be very rare.

It was too common before, and there was exploits people were using to farm these chests. As more set pieces are added I do plan to increase the odds.

Everything balance wise done is done for a reason, just because you don’t see it for your use case, it does not mean that it is not required, as Adventure that to account for the usage across every bot that uses it and not just TrustyBot.

**Comment by mattpilf** [comment]
Since the update, so a week. Nobody that we know in the dozens of people over multiple servers, killing idk how many dragons at this point (certainly fought over 100 and tend to have above 50% success rates).

**Comment by kwando1313** [comment]
Yeah, I’d say at least 50+ dragons that we’ve killed over the span of a week and we’ve seen 0 set chests.

**Comment by Drapersniper** [comment]
Okay, so you are saying that even though you killed 50 dragons in 6 days, that’s 8.3 bosses per day,  that’s 41 minutes play time being bosses per day. 

Imo that’s too common, as an alternative could make bosses drop 1 chest per kill that’s rolled between players, and limit the number of bosses a player can join to one per week.  

Like I said your current feedback is because you became a customised to an abundance of set chests, and that has since been rebalanced to account for their higher bonuses and stats now.

Other than trustybot users no one else has raised any concerns with rarity of set chests, I will ask around but at the moment I don’t see an issue here

**Comment by Drapersniper** [comment]
Addres by #136

**Comment by aikaterna** [comment]
There was a compromise made and Draper's PR at #136 actually includes a higher set bonus than Trusty's did. Draper's PR was merged as this was more favorable to Trusty than his PR in #135.
