### ISSUE TITLE
Exp and leveling

### ISSUE THREAD

**Issue by Meep85** [aikaterna/gobcog#154]
It seems leveling is completely broken. Some people are requiring 5million exp. for one level and hunter pets now do nothing. I have not gotten a level in hours!!! Most people on my server have gone inactive as it is no longer fun.

**Comment by Meep85** [comment]
Make that 17 million exp...

**Comment by Emre-desertbird** [comment]
I don't think it's broken, just exaggerated.
I'm sure people in strong and/or large servers leveled up too fast and that the exp to next level were raised by a lot (I think you need 10 times the old amount of xp to level up now)...
Problem is, servers with not that many adventure players suffer from that quite a lot. Since the xp increase I (and most of the other adventure players on my server) didn't even level up once, since we just did about 20 adventures a day... Now we have like 4 adventures a day and even less players because almost everyone lost their motivation.

**Comment by Meep85** [comment]
Either way you have to look at it this way: not fun is broken. Everyone that I play with has either already lost intrest or is in the process of losing intrest.

**Comment by Emre-desertbird** [comment]
One way to fix this would be adding an adventure-command for multiplying ALL exp-gain, so that everyone is happy...

**Comment by Menteroth** [comment]
There was a discussion about this on Discord yesterday where this was explained. It won't be that much exaggerated XP every level.

https://ptb.discordapp.com/channels/240154543684321280/240154911449284620/691842390268575795

**Comment by Meep85** [comment]
It is still gonna take about 2 weeks for me to get my next level. That is not fun.

**Comment by Drapersniper** [comment]
Then you arent making use of the avaliable functions of adventure 🤷 

are you level you arent supposed to get a level in 1  adventure...
you aren supposed to cheese and game and let lower level players start the adventure
Some classes level faster than others.

It is not broken period.


if you you are soooooooooooo bothered about it why dont you start by giving actuare details so that it can actually be looked into for example
1 - My level is x 
2 - My XP to get next level is X 
3 - I have x rebirths
4 - This is my current gear and stats and class

@Meep85

**Comment by Drapersniper** [comment]
User did not reply, this issue is stale.
will not be working on it for the test release
