### ISSUE TITLE
Reloading cog no longer ends existing adventure?

### ISSUE THREAD

**Issue by Skyrid3r** [aikaterna/gobcog#166]
In the past, when an adventure was started. You were able to reload the cog which would end any current running adventure. However, now the adventure description/reactions  & timer just freezes.

![image](https://user-images.githubusercontent.com/6794064/81493662-9a576f00-92a2-11ea-8ee4-ddd58711d2a0.png)

Is this intended?

**Comment by aikaterna** [comment]
You kill all tasks when you reload the cog, including the timer. Reloading a cog is never an intended method of using a cog, and if it needs to be reloaded something is wrong. This is a non issue to me because the cog can't be expected to continue working with something it was aware of before a reload, once said reload happens. The behavior of the adventure during a reload is not something that will be visited unless there is something legitmately wrong.
