### ISSUE TITLE
Recent update ruined the game 

### ISSUE THREAD

**Issue by justinfello** [aikaterna/gobcog#295]

**Comment by aikaterna** [comment]
Leave an issue with more details next time.

**Comment by Drapersniper** [comment]
Please to enlighted me on how it ruined the game?

As you but hurt you are loosing items to negas? well stop being a dumb shit and play it properly.

Are you but hurt transfer are taxed? dont give a fuck speak to your bot owner.


in other words ... get fucked, because i couldnt give a flying shit to what you think 🤷
