### ISSUE TITLE
Feedback Received for update... And my expe

### ISSUE THREAD

**Issue by skylarr1227** [aikaterna/gobcog#85]
* Level reqs are a tad off. Need to be adjusted otherwise starting is almost impossible. 
* For example: Normal Chests will give items with 0, 0, 0 , 0, 0 stats that require level 6-10... yet are useless... And then also will give a blue item, that has 0, 0, 2, 2, 0 or similar and requires level 22-29. (umm what?)
![2020-01-25 16_48_28-#general•chat - Discord](https://user-images.githubusercontent.com/44381751/73127717-b86abf00-3f92-11ea-8407-3fdabd32b5c4.png)
There is no middle ground.
* The only thing that Useless items could possibly be even in the game for would be to sell for $$$, however nearly all of them sell for 0... and even some of the blues requiring level 25-30 sell for 0.
![2020-01-25 16_47_46-#general•chat - Discord](https://user-images.githubusercontent.com/44381751/73127718-bdc80980-3f92-11ea-8c98-b930c4999441.png)
![2020-01-25 16_52_17-#general•chat - Discord](https://user-images.githubusercontent.com/44381751/73127740-1697a200-3f93-11ea-9585-94e26934b977.png)
![2020-01-25 16_52_00-#general•chat - Discord](https://user-images.githubusercontent.com/44381751/73127741-19929280-3f93-11ea-90ad-944dd6a37899.png)

**Comment by skylarr1227** [comment]
im trying to find some sort of fix for this by looking it over, but it seems like this may be an issue that isnt just a simple fix

**Comment by GoaFan77** [comment]
How were these items generated? It looks like most of them have it in the form {singlestat: 0}. E.g. 

`panified duranium collar": {"slot": ["neck"], "att": 0}`

Even if the items cannot be regenerated with a minimum stat, I quick bit of code should be able to parse these and update any that have 0 stats with 1 to the stat they have listed.

This is definitely a HUGE issue for my group with the new version. Loot is often frustrating instead of rewarding, people are getting through 30 levels with almost no gear. Ranger pet foraging is a joke.

**Comment by Drapersniper** [comment]
This is intentional that  some items have 0 stats.

**Comment by Drapersniper** [comment]
Also worth mentioning .......
If you dislike the Default Theme, You can create your own with items that have stats you are happier with

**Comment by Drapersniper** [comment]
> It looks like most of them have it in the form {singlestat: 0}. 
This is very innacurate.

Common items:
23106 - Items with at least 1 0 start stat
60547 - Items with no 0 start stat

Rare items:
2880 - Items with at least 1 0 start stat
80868  - Items with no 0 start stat

Epic Items:
3043 - Items with at least 1 0 start stat
80667 - Items with no 0 start stat

Legendary items:
4222 - Items with at least 1 0 start stat
83555 - Items with no 0 start stat

**Comment by Drapersniper** [comment]
@skylarr1227 
>  And then also will give a blue item, that has 0, 0, 2, 2, 0 or similar and requires level 22-29. (umm what?)

According to your screenshot this is a lie ... 2 2 0 1 3 is a Level 16 items, so  how is a 0 0 2 2 0 a level 29 ... unless you are over exagerating to make a point please show a screenshot of this if you aren't over exagerating. 

> There is no middle ground.

this is wrong. since item stats are in a range so there will always be items that have lower and higher level requirements.

> The only thing that Useless items could possibly be even in the game for would be to sell for $$$, however nearly all of them sell for 0... and even some of the blues requiring level 25-30 sell for 0.

Item with 0 stats sell for 0 yes, if they dont have 0 stats thats a no.

> The only thing that Useless items could possibly be even in the game for would be to sell for $$$

This is wrong, these could be used for tinkerers, boasting factor, some other features im working on

**Comment by skylarr1227** [comment]
My question here is Why you continued this, or replies when you and I had already spoken on this- and when I already had resolved the issue in full. Just silly crap.... Many times over i don't get it.

**Comment by GoaFan77** [comment]
> This is intentional that some items have 0 stats, and nothing mentioned here is a Bug or issue, it was intentionaly done.
> 
> There are over 300K new items, loot is more randomzied, and all items have a range their attributed could be.
> 
> > Normal Chests will give items with 0, 0, 0 , 0, 0 stats that require level 6-10.
> 
> What are the rarity of these items?

Can you please elaborate why this is intentional? My entire group finds this frustrating and assumes it's a bug.

The way I see it, loot is a reward for players to get exited for and encourage continued play and a sense of progress. Statless items do none of these things, it just feels like a joke.

I don't see how this helps tinkerers either unless the forge mechanics are entirely different now. Maybe to change the slot type, but even then they will likely want to use items with actual stats as soon as possible.

Ranger foraging also feels worthless half the time when these items are found.

This update also has the rebirth mechanic to frequently purge gear. People are getting to level 20-30 without any actual gear at all.

I realize the items are customizable, and that's good. But my initial impression is that this is a terrible default, unless there is some game design factor I am not considering.

**Comment by Drapersniper** [comment]
> My question here is Why you continued this, or replies when you and I had already spoken on this- and when I already had resolved the issue in full. Just silly crap.... Many times over i don't get it.

This was to contextualise reasoning and so people have context “silly” is contextual and you are free to believe so, might be a surprise but you aren’t the only adventure user that follows this repo

**Comment by Drapersniper** [comment]
> > This is intentional that some items have 0 stats, and nothing mentioned here is a Bug or issue, it was intentionaly done.
> > There are over 300K new items, loot is more randomzied, and all items have a range their attributed could be.
> > > Normal Chests will give items with 0, 0, 0 , 0, 0 stats that require level 6-10.
> > 
> > 
> > What are the rarity of these items?
> 
> Can you please elaborate why this is intentional? My entire group finds this frustrating and assumes it's a bug.
> 
> The way I see it, loot is a reward for players to get exited for and encourage continued play and a sense of progress. Statless items do none of these things, it just feels like a joke.
> 
> I don't see how this helps tinkerers either unless the forge mechanics are entirely different now. Maybe to change the slot type, but even then they will likely want to use items with actual stats as soon as possible.
> 
> Ranger foraging also feels worthless half the time when these items are found.
> 
> This update also has the rebirth mechanic to frequently purge gear. People are getting to level 20-30 without any actual gear at all.
> 
> I realize the items are customizable, and that's good. But my initial impression is that this is a terrible default, unless there is some game design factor I am not considering.

In regards to this, the idea was so that not every item will be useful for every player. Some 0 stats items also have benefits such as helping against the monsters such as the basilisk.

No RPG has all their item be beneficial, item it’s a roll it may be good and it may not be good. And as it was further explained on my other message most of the items don’t have have 0 stats. 

And the higher level and more rebirths and better the monsters you are killing the better items you will get.

**Comment by GoaFan77** [comment]
Not useful for every player is fine. Not useful for ANY player is not fine in my opinion.

Mirror shield had stats last version I believe, and while one or two special items with no stats but some hidden use is fine (though given how many items are available now, maybe not a great design), the drop percentage of useless items from normal chests is way too high.

I fully realize it's likely a non-issue at higher rebirth, but I am telling you at just a few rebirths it's not fun. And if the early game is not fun, people will quit and never see all the cool new set bonuses or whatever else was added.
