### ISSUE TITLE
Pet Taming problems

### ISSUE THREAD

**Issue by skylarr1227** [aikaterna/gobcog#95]
So I've noticed that pets are extremely hard to tame, which I had attributed to the fact that were so many total and my charisma stat (still called diplomacy some places for whatever reason) was low.

Well I was testing this morning, with 211 charisma... Which according to the data json file for pets should be enough to tame more than half of the entire list of pets (almost) and still noticed I was failing to tame things such as a Desert Armadillo for example, which the json says requires 15 Cha. 

This isn't making a whole lot of sense, am I missing something?
![Screenshot_20200209-140818](https://user-images.githubusercontent.com/44381751/74110973-eccba700-4b5e-11ea-8475-513b505c5bde.png)

**Comment by Emre-desertbird** [comment]
I think that's intended.

>if dipl_value > self.PETS[pet]["cha"] and roll > 1:
                    roll = random.randint(0, 2 if roll == 20 else 4)
                    if roll == 0:
                        pet_msg3 = box(
                            _("{bonus}\nThey successfully tamed the {pet}.").format(
                                bonus=bonus, pet=self.PETS[pet]["name"]
                            )<

So if your diplomacy (+int/3+luck/2+roll) is enough there is a 1/4 chance to get the pet normally and 1/2 if you rolled a 20.

**Comment by skylarr1227** [comment]
So even if someone has 200+ charisma, its only a 1/4 chance - and a 50% chance if you roll a 20?
Because i was under the impression that 20 = you get +10 for having favorite food.
1 = -10 to char for breaking a twig.

I see no reason why someone with 200 charisma should Ever fail taming something that requires 15

**Comment by skylarr1227** [comment]
With a 2 hour cooldown, this means your chances to tame a pet that actually is your charisma level would be .0001% or something crazy. More than likely, every single time, your gonna get something WAY lower than your charisma level.... if you succeed at all.

**Comment by Emre-desertbird** [comment]
Well you will get something good eventually... But ranger rn is pretty okish.

With low cha you will get moths or something like that after like 200 tries (which is not a big problem since it doesn't trigger cooldown imo, but annoying), that can get you gear which is good since rarity of chests in general went down (big step up compared to old ranger)...
You also get bonus credits (which is meh, but better than nothing) and bonus xp (which is pretty good), depending on what pet you have. Low cha pets give you almost nothing, but there are a few who stand out (pygmy unicorn and pocket dragon).

And with high cha you have a good chance to get Albedo and Rubedo, with are both pretty damn good.

I still agree, that it could be better, since there are a lot of crappy pets with high cha, but I don't think ranger is bad right now because of that.

**Comment by skylarr1227** [comment]
It absolutely does trigger cooldown. What are you talking about?

**Comment by Emre-desertbird** [comment]
I mean cooldown only triggers when you catch a pet...
Anyway, since you keep a ranger pet forever (except when you release it), I think it's okey if it's hard to catch a good pet, even tho it's annoying.

**Comment by Emre-desertbird** [comment]
If you failed 40+ times, it was extremely unlucky. Even my mediocre-cha (50-100) friend almost always just has to try ~10-20 times

**Comment by Drapersniper** [comment]
As @Emre-desertbird Pointed out .. this is 100% intentional, and cooldown only triggers upon capturing a pet successfully, if this is not the case please file an issue with the exact reproduction steps and screenshots.
